class Receipe {
  String? receipeId;
  String? receipeName;
  String? receipeDrinkAlternate;
  String? receipeCategory;
  String? receipeArea;
  String? receipeInstructions;
  String? receipeImg;
  String? receipeTags;
  String? receipeYoutube;
  String? receipeIngredient1;
  String? receipeIngredient2;
  String? receipeIngredient3;
  String? receipeIngredient4;
  String? receipeIngredient5;
  String? receipeIngredient6;
  String? receipeIngredient7;
  String? receipeIngredient8;
  String? receipeIngredient9;
  String? receipeIngredient10;
  String? receipeIngredient11;
  String? receipeIngredient12;
  String? receipeIngredient13;
  String? receipeIngredient14;
  String? receipeIngredient15;
  String? receipeIngredient16;
  String? receipeIngredient17;
  String? receipeIngredient18;
  String? receipeIngredient19;
  String? receipeIngredient20;
  String? receipeMeasure1;
  String? receipeMeasure2;
  String? receipeMeasure3;
  String? receipeMeasure4;
  String? receipeMeasure5;
  String? receipeMeasure6;
  String? receipeMeasure7;
  String? receipeMeasure8;
  String? receipeMeasure9;
  String? receipeMeasure10;
  String? receipeMeasure11;
  String? receipeMeasure12;
  String? receipeMeasure13;
  String? receipeMeasure14;
  String? receipeMeasure15;
  String? receipeMeasure16;
  String? receipeMeasure17;
  String? receipeMeasure18;
  String? receipeMeasure19;
  String? receipeMeasure20;
  String? receipSource;
  String? receipeImageSource;
  String? receipeCreativeCommonsConfirmed;
  String? receipeModified;

  factory Receipe.fromJson(Map<String, dynamic> json) {
    return Receipe();
  }
}
